### PR TITLE
Added simple wsgi.py file for use with Apache or other servers

### PR DESCRIPTION
**Pull request by mikeshultz**
Simple wsgi file.  Tested and works.

### CODE REVIEW

**Comment by shrayasr** [comment]
Thanks for this @mikeshultz :+1: 

Will it work even if LSQ is installed inside a virtual environment? There seems to be some pointers [here](http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/#working-with-virtual-environments) which involves an absolute path

**Comment by mikeshultz** [comment]
Depends on the server configuration.  Should be irrelevant for this file.  You can look up wsgi for nginx, apache, etc for more information.

**Comment by shrayasr** [comment]
> You can look up wsgi for nginx, apache, etc for more information.

I've looked up some stuff [here](https://code.google.com/p/modwsgi/wiki/VirtualEnvironments) and [here](http://stackoverflow.com/questions/4614121/running-python-from-a-virtualenv-with-apache-mod-wsgi-on-windows). One of them mention setting the `WSGIPythonHome` to the right path inside the virtual environment and the other recommends to modify the wsgi file and add a few lines with an absolute path. 

I feel like i'm missing out on something. This is my first adventure with WSGI so any resources you could point me towards would be much appreciated. Thanks!

**Comment by mikeshultz** [comment]
Yeah, virtualenvs are special stuff and I have not yet gotten them to work with Apache.  It probably doesn't require mods to wsgi.py, but like I said, I never got it to work properly.  

Only time I've gotten it to work  with virtualenv so far was with uwsgi.  So I'm not the greatest person to ask about that.

Running outside of a virtualenv should work as expected.

**Comment by shrayasr** [comment]
Adding a line which adds the current directory to path seems to be the [most preferred](https://github.com/search?q=sys.path.insert%280%2C+os.path.dirname%28__file__%29%29+wsgi&ref=searchresults&type=Code&utf8=%E2%9C%93) approach ATM. 

Also, I see that most of the code at @hasgeek (An event organizing company in India whose stack is predominantly python and flask) uses [this](https://github.com/hasgeek/hasjob/blob/master/website.py) [same](https://github.com/hasgeek/funnel/blob/master/website.py) [approach](https://github.com/hasgeek/lastuser/blob/master/website.wsgi). 

These two are good enough reasons for me to think that adding the line: 

``` python
sys.path.insert(0, os.path.dirname(__file__))
```

can deal with the issue to quite a large extent. 

If you can please add this in and update the PR, I'll be more than glad to merge it in :smile:

**Comment by mikeshultz** [comment]
Added.

**Comment by shrayasr** [comment]
Thanks :+1: :shipit:

**Pull request merged**
